### PR TITLE
fix: macOS compilation error with EINTR in checkWait

### PR DESCRIPTION
**Pull request by jasagiri**
There are major changes being made to the response, so if it's outside the scope, it might be better to wait until things have settled down before merging. I'll submit a PR for now, so please merge if necessary.

### CODE REVIEW

**Comment by disruptek** [comment]
OSX support is not a priority, but I don't see any reason we cannot make a reasonable effort to accommodate it, and thank you for your service!

**Comment by disruptek** [comment]
We need this for the balls merge, eh?

**Comment by jasagiri** [comment]
Yes, merging this insideout PR first would be ideal — balls PR #77 currently duplicates the macOS type definitions (`signalfd_siginfo`, kqueue constants, etc.) in its own `darwin.nim`. Once this insideout PR is merged, balls can import those types directly from insideout instead of maintaining a separate copy.

That said, balls PR #77 currently works independently with its own `darwin.nim`, so it's not strictly blocked. But merging this first would allow cleaning up the duplication in balls.

File: insideout/futexes.nim [hunk 1]
```diff
@@ -81,10 +123,11 @@ proc waitMask*[T](monitor: var Atomic[T]; compare: T; mask: uint32;
...
       var tm: TimeSpec
-      try:
-        vm = getTimeSpec(CLOCK_MONOTONIC) + timeout.toTimeSpec
-      except OSError as e:
-        raise FutexError.newException $e.name & ":" & e.msg
+      # try:
+      #   tm = getTimeSpec(CLOCK_MONOTONIC) + timeout.toTimeSpec
+      # except OSError as e:
+      #   raise FutexError.newException $e.name & ":" & e.msg
+      tm = timeout.toTimeSpec
```
Comment (disruptek) [inline insideout/futexes.nim]: Let it crash (and/or fix it); this change just introduces cruft.

File: insideout/futexes.nim [hunk 2]
```diff
@@ -109,19 +152,25 @@ proc wakeMask*[T](monitor: var Atomic[T]; mask: uint32; count = high(int32)): ci
...
-    result = errno
-    case errno
-    of EINTR, EAGAIN, ETIMEDOUT:
+    let e = errno
+    result = e
+    if e == EINTR or e == EAGAIN or e == ETIMEDOUT:
       discard
     else:
-      raise FutexError.newException $strerror(errno)
+      raise FutexError.newException $strerror(e)
```
Comment (disruptek) [inline insideout/futexes.nim]: I prefer my version.  Also, why?

File: insideout/mailboxes.nim [hunk 3]
```diff
@@ -230,8 +230,7 @@ proc performWait[T](mail: Mailbox[T]; has: uint32; wants: uint32): bool {.discar
   result = 0 == (has and wants)
   if result:
     let e = checkWait waitMask(mail[].state, has, wants)
-    case e
-    of EINTR:
+    if e == EINTR:
```
Comment (disruptek) [inline insideout/mailboxes.nim]: No.

File: insideout/futexes.nim [hunk 4]
```diff
@@ -109,19 +152,25 @@ proc wakeMask*[T](monitor: var Atomic[T]; mask: uint32; count = high(int32)): ci
...
   else:
     result = err
 
 proc checkWake*(err: cint): cint {.discardable.} =
   if -1 == err:
-    result = errno
```
Comment (disruptek) [inline insideout/futexes.nim:123]: You're changing the behavior on Linux and again using a gratuitous extra variable.  I'm going to need more justification than whatever this comment is supposed to tell me.

You can use a `when` here to define special behavior for macOS; the `else` should reproduce the original behavior.

File: insideout/runtimes.nim [hunk 5]
```diff
@@ -23,7 +23,13 @@ export coop
...
 const insideoutDeferredCancellation* {.booldefine.} = false
 
-let insideoutInterruptSignal* = SIGRTMIN
+when defined(macosx) or defined(darwin) or defined(bsd):
+  let insideoutInterruptSignal* = SIGUSR1
+elif defined(linux):
+  let insideoutInterruptSignal* = SIGRTMIN
+else:
+  let insideoutInterruptSignal* = 31.cint
+
```
Comment (disruptek) [inline insideout/runtimes.nim:32]: You can define special behavior for macosx/darwin/bsd.  The rest of the world gets the original behavior.

File: insideout/runtimes.nim [hunk 6]
```diff
@@ -192,10 +198,9 @@ proc waitForFlags(runtime: var RuntimeObj; mode: WaitMode; wants: uint32): bool
         checkWait waitMask(runtime.flags, has, wants and not has)
       except FutexError as e:
         raise RuntimeError.newException $e.name & ":" & e.msg
-    case err
-    of 0, EINTR, EAGAIN:
+    if err == 0 or err == EINTR or err == EAGAIN:
       discard
-    of ETIMEDOUT:
+    elif err == ETIMEDOUT:
```
Comment (disruptek) [inline insideout/runtimes.nim]: No.

File: insideout/runtimes.nim [hunk 7]
```diff
@@ -449,10 +454,10 @@ proc loop(eq: var EventQueue; runtime: var RuntimeObj): cint =
       if flags && <<!Frozen:
         phase = CheckState
       else:
-        case checkWait waitMask(runtime.flags, flags, <<Halted + <<!Frozen)
-        of EINTR:
+        let e = checkWait waitMask(runtime.flags, flags, <<Halted + <<!Frozen)
+        if e == EINTR:
           discard
-        of 0, EAGAIN:
+        elif e == 0 or e == EAGAIN:
```
Comment (disruptek) [inline insideout/runtimes.nim]: No.

File: insideout/runtimes.nim [hunk 8]
```diff
@@ -461,7 +466,7 @@ proc loop(eq: var EventQueue; runtime: var RuntimeObj): cint =
               FrozenPhase              # loop and don't rename thread
             else:                      # unfrozen
               CheckState
-        of ETIMEDOUT:
+        elif e == ETIMEDOUT:
```
Comment (disruptek) [inline insideout/runtimes.nim]: Also no.

File: insideout/runtimes.nim [hunk 9]
```diff
@@ -526,13 +525,13 @@ proc defaultSignalHandler(runtime: Runtime; fd: Fd) {.cps: Continuation.} =
...
-    of SIGINT:
+    let s = info.ssi_signo.cint
+    if s == SIGINT:
       # if we're here, well, mission accomplished
       discard
-    of SIGTERM, SIGQUIT:
+    elif s == SIGTERM or s == SIGQUIT:
       halt runtime
-    of SIGCONT:
+    elif s == SIGCONT:
```
Comment (disruptek) [inline insideout/runtimes.nim]: No.

File: insideout/runtimes.nim [hunk 10]
```diff
@@ -600,7 +606,8 @@ proc boot(runtime: var RuntimeObj; size = insideoutStackSize)
   let mask = signalMask runtime
   var attr {.noinit.}: PThreadAttr
   spawnCheck pthread_attr_init(addr attr)
-  spawnCheck pthread_attr_setsigmask_np(addr attr, addr mask)
+  when not defined(macosx) and not defined(darwin):
+    spawnCheck pthread_attr_setsigmask_np(addr attr, addr mask)
```
Comment (disruptek) [inline insideout/runtimes.nim:667]:
```
when defined(osx...darwin...bsd?)
  discard
else:
  set signal mask
```

File: insideout/runtimes.nim [hunk 11]
```diff
@@ -619,10 +626,9 @@ proc boot(runtime: var RuntimeObj; size = insideoutStackSize)
       except FutexError as e:
         raise SpawnError.newException e.msg
         errno
-    case err
-    of 0, EINTR, EAGAIN:
+    if err == 0 or err == EINTR or err == EAGAIN:
       discard
-    of ETIMEDOUT:
+    elif err == ETIMEDOUT:
```
Comment (disruptek) [inline insideout/runtimes.nim]: No.

File: tests/t00_futexes_macos.nim [hunk 12]
```diff
@@ -0,0 +1,17 @@
...
+    var x: Atomic[uint32]
+    store(x, 1, order = moSequentiallyConsistent)
+    # タイムアウトの確認
+    check checkWait(wait(x, 1, timeout = 0.01)) == ETIMEDOUT
+    # 値の不一致（EAGAIN）の確認
+    store(x, 2, order = moSequentiallyConsistent)
+    check checkWait(wait(x, 1, timeout = 0.01)) == EAGAIN
+    # waitMaskの不一致確認
+    let res3 = waitMask(x, 2, 4)
+    check checkWait(res3) == EAGAIN
```
Comment (disruptek) [inline tests/t00_futexes_macos.nim]: I need better comments at the top of the file explaining what semantics you're trying to assert here, and why; should the test be guarded by a `when` for your platforms?

File: tests/t30_runtimes_macos.nim
Comment (disruptek) [inline tests/t30_runtimes_macos.nim:1]: Same deal here.

File: tests/t90_sleep_macos.nim
Comment (disruptek) [inline tests/t90_sleep_macos.nim:1]: And here.

File: tests/t99_signals_macos.nim
Comment (disruptek) [inline tests/t99_signals_macos.nim:1]: And here.

File: MACOS.md
Comment (disruptek) [inline MACOS.md:1]: Merge this into the README.md

File: insideout/eventqueue.nim [hunk 13]
```diff
@@ -475,13 +618,94 @@ proc cancel*(eq: EventQueue; id: Id): bool {.discardable.} =
...
+    result = nil
+  
+  
 proc sleep*(eq: EventQueue; timeout: float) {.cps: Continuation.} =
   ## sleep for `timeout` seconds
-  var fd = timerfd_create(CLOCK_BOOTTIME, TFD_NONBLOCK or TFD_CLOEXEC).Fd
-  var it: itimerspec
-  it.it_value = timeout.toTimeSpec
-  checkErr timerfd_settime(fd, 0, addr it, nil)
-  discard eq.register(fd, {Read, OneShot})
```
Comment (disruptek) [inline insideout/eventqueue.nim:484]: This is an accident waiting to happen; guard your platforms, and the rest of the world gets "linux" behavior.  Here you are not making an exhaustive assignment.

File: insideout/eventqueue.nim [hunk 14]
```diff
@@ -374,36 +496,50 @@ proc initEventQueue*(): EventQueue =
...
+    if event.filter == EVFILT_TIMER:
+      result.incl Read
+    if (event.flags and EV_ERROR) != 0:
+      result.incl Error
+    if (event.flags and EV_EOF) != 0:
+      result.incl HangUp
+    if (event.flags and EV_CLEAR) != 0:
+      result.incl Edge
+
+proc runEvent(eq: var EventQueueObj; event: var EventInfo) {.deprecated.} =
```
Comment (disruptek) [inline insideout/eventqueue.nim]: Move these into inline functions so you can write a simple `when` guard for your platforms.  The rest of the world gets the default linux behavior.

File: insideout/eventqueue.nim [hunk 15]
```diff
@@ -425,34 +561,41 @@ proc pruneOneShots(eq: var EventQueueObj; events: var openArray[epoll_event];
...
+    result = epoll_pwait2(eq[].interest.cint, cast[ptr epoll_event](addr events[0]),
+                          events.len.cint, timeout, mask)
+  elif defined(macosx) or defined(darwin) or defined(bsd):
+    # kqueue doesn't have pwait2 equivalent that takes a signal mask directly
+    # in the same way, but we can set the signal mask for the thread.
+    # However, insideout seems to already do that in runtimes.nim.
+    result = kevent_proc(eq[].interest, cast[ptr kevent](addr events[0]), 0,
+                    cast[ptr kevent](addr events[0]), events.len.cint, timeout)
+
+proc wait*(eq: var EventQueue; events: var openArray[EventInfo];
```
Comment (disruptek) [inline insideout/eventqueue.nim]: Guard your platforms, not mine.

**Review by disruptek — CHANGES_REQUESTED** [review]
Basically, I don't want `when` guards on Linux; I want them on macOS etc.
Don't change my `case` style for `if`; there's a reason I use `case` -- it more elegantly captures the exact semantic I'm trying to convey to the compiler.  You are welcome to use an `if` ladder on macOS if you so choose.

I don't run macOS so I don't care if it works, but I'd like an AI to be able to service it for us, and without consuming the entire codebase.  Be specific in the comments (in the impl) with respect to your intentions and be specific with respect to the developer experience in the README.md.

**Comment by jasagiri** [comment]
Thanks for the thorough review — the direction was clear. I've reworked the
branch; here's what changed.

### Platform guards now wrap macOS/BSD, with Linux as the default

Every `when defined(linux): … elif macos: …` is inverted to
`when defined(macosx) or defined(darwin) or defined(bsd): … else: …`, so the
`else` branch reproduces the original Linux behavior verbatim — no `when`
guards sit on the Linux path. This covers `eventqueue.nim` end to end (header
imports, type defs, `register`, `toSet`, `wait`, `sleep`, `init`,
`delRegistry`) and `runtimes.nim` (`insideoutInterruptSignal` falls back to
`SIGRTMIN`; `pthread_attr_setsigmask_np` is guarded macOS-first).

### `case` statements restored

I reverted every `case` → `if` change. Your `case` is kept unchanged as the
default path; the `if` ladder appears only inside a `when defined(macosx)`
guard.

The reason the `if` ladder is unavoidable on macOS: `std/posix` defines
`EINTR`/`SIGTERM`/etc. as compile-time `const`s on Linux, but as `importc`
variables on macOS — and `importc` variables cannot appear in `case`
branches. I confirmed this by compiling the unmodified master `futexes.nim`
with Nimskull targeting macOS, which fails with
`cannot evaluate at compile time: EINTR`. So on Linux your `case` compiles
exactly as before; only macOS needs the `if` form.

### `composeEvent` / `waitMask` cruft removed

- `composeEvent` is restored; the macOS path builds `kevent`s in its own
  `when` branch instead.
- `waitMask` no longer alters the Linux timeout semantics — the absolute
  `CLOCK_MONOTONIC` deadline (and its `try`/`except`) is preserved on Linux;
  the relative-duration form is Darwin-only. The `vm` typo is fixed and the
  commented-out block is gone.

### Docs & tests

- `MACOS.md` is merged into a dedicated **macOS** section of `README.md`,
  covering the emulation strategy and the macOS developer experience (build
  flags, the undocumented-`__ulock` caveat and its risks).
- Each `t*_macos.nim` test now has a header explaining what it asserts and
  why, and is `when`-guarded to Darwin/BSD so it's inert on other platforms.
- Fixed a latent bug in `t00`: `waitMask(x, 2, 4)` compared `x` against its
  own current value, falling through to an un-woken `wait` that blocked
  forever; it now uses a guaranteed mismatch.

I verified my changes compile under Nimskull (macOS) for all four touched
files, and the macOS test suite passes under mainline Nim 2.2.8.

File: insideout/futexes.nim [hunk 16]
```diff
@@ -39,14 +39,56 @@ const
...
+  let NR_Futex {.importc: "__NR_futex", header: "<sys/syscall.h>".}: cint
+  proc syscall(sysno: clong): cint {.header:"<unistd.h>", varargs.}
+
+  proc sysFutex(uaddr: pointer; futex_op: cint; val: uint32;
+                timeout: ptr TimeSpec = nil; uaddr2: ptr uint32 = nil;
+                val3: uint32 = 0): cint =
+    assert val != 0
+    result = syscall(NR_Futex, uaddr, futex_op, val, timeout, uaddr2, val3)
+
+elif defined(macosx) or defined(darwin):
```
Comment (disruptek) [inline insideout/futexes.nim:52]: Guard your platforms, not mine.

**Review by disruptek — CHANGES_REQUESTED** [review]
Let's see if we can trigger CI on it this time.

**Comment by jasagiri** [comment]
Quick status on CI: there's no workflow run against the current head
(7ea4222) — the PR's checks are empty, and there's no pending or
approval-required run for that SHA. Pushing the branch is a `synchronize`
event, and that didn't produce a run this time, even though earlier pushes
on this branch did run CI back in March.

That leaves me with few levers on my side, since re-pushing is the same
`synchronize` event that isn't catching. I can try closing and reopening the
PR (a `reopened` event) if you think that's worth a shot. Otherwise this
likely needs a look from your end — re-running from the Actions tab, or a
glance at the repo's fork-PR workflow settings. The branch is mergeable and
sits on the current master tip (1.0.9). Happy to follow your lead.

**Comment by disruptek** [comment]
It seems nimskull is breaking the ecosystem in order to switch from nimble to a new package manager which requires std/ prefix on stdlib imports.

I assume you're using mainline nim?  Which version?  Want to update the CI to point to it?

**Comment by jasagiri** [comment]
Yes — I'm on mainline Nim 2.2.8 (macOS arm64).

Before flipping the CI matrix over, one compatibility wrinkle worth flagging:
mainline Nim's `std/posix` defines `EINTR`/`SIGTERM`/etc. as `importc`
variables (not compile-time `const`s as Nimskull does on Linux). That means
`case errno of EINTR, EAGAIN, ETIMEDOUT:` — including several spots in your
current `master` (`futexes.checkWait`, `runtimes.waitForFlags`/`loop`/
`defaultSignalHandler`/`boot`, `mailboxes.performWait`) — won't compile on
mainline:

    Error: cannot evaluate at compile time: EINTR

I confirmed this both ways: unmodified `master/futexes.nim` compiles under
Nimskull (stdlib `EINTR` is a `const` there) but fails under mainline Nim
2.2.8. My PR already sidesteps the problem on macOS via an `if` ladder under
`when defined(macosx)`, but keeps your `case` on the Linux/Nimskull path.
Re-pointing CI at mainline will surface the same problem on Linux.

So before I touch ci.yml, which way do you want this:

(a) Switch the matrix to mainline Nim **and** convert the remaining Linux
    `case` blocks to `if` ladders to match (mechanical change in three files).
(b) Run the matrix on both Nimskull and mainline so regressions on either
    side get caught.
(c) Hold the CI change until the Nimskull/nimble situation settles.

Happy to do (a) or (b) — just want to confirm before turning the `case`
statements you specifically asked me to preserve.
